version: '3.8'

services:
  backend:
    build: .
    container_name: eticaret-backend
    ports:
      - "3000:3000"
    environment:
      - DB_NAME=eticaret
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - JWT_SECRET=gizli_anahtar
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: eticaret-postgres
    environment:
      POSTGRES_DB: eticaret
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: eticaret-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: eticaret-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata: 